[AC-xx: cicd]  EKS - Add dockerfile, jenkinfile and deployment file
A-Comosus/comosus-server pull request #20
Opened 2022-06-28 09:52 UTC by mable-pmyip

### Provide description as to what you have done in this pr.
Add dockerfile, jenkinfile and deployment file 
### Provide screenshots or videos that the function is working.
![image](https://user-images.githubusercontent.com/94888732/177004981-0a75ced7-fa55-4211-bbfe-ad966c22cd0d.png)

### Provide screenshots of no warning, error in console.
![image](https://user-images.githubusercontent.com/94888732/177318682-8f4f1c30-3e72-435e-9463-c6d626d2bcc9.png)

2022-06-28 09:58 UTC, mable-pmyip commented on CI-CD/Jenkinsfile.Mable
> +				dockerImage = docker.build( appRegistry + ":$BUILD_NUMBER", "-f Dockerfile.Alex .")
my dockerfile was working last week but not sure why doesn't work recently, stole from Alex for now :P

2022-06-28 11:07 UTC, tardigrade425 requested changes

2022-06-28 11:07 UTC, tardigrade425 commented on CI-CD/Jenkinsfile.Mable
> +				dockerImage = docker.build( appRegistry + ":$BUILD_NUMBER", "-f Dockerfile.Alex .")
禁止引用他人名称文件

2022-07-01 09:47 UTC, tardigrade425 requested changes

2022-07-01 09:47 UTC, tardigrade425 commented on Dockerfile.Mable
> +# for primas
Secrets不允许明文出现在Repo中

2022-07-01 09:47 UTC, tardigrade425 commented on deployment.yaml
> +    app: comosus-server
这是deploy to个人的还是项目的？

2022-07-02 12:39 UTC, mable-pmyip commented on deployment.yaml
> +    app: comosus-server
个人的

2022-07-02 12:39 UTC, mable-pmyip commented on CI-CD/Jenkinsfile.Mable
> +				dockerImage = docker.build( appRegistry + ":$BUILD_NUMBER", "-f Dockerfile.Alex .")
updated to my dockerfile

2022-07-02 12:39 UTC, mable-pmyip commented on Dockerfile.Mable
> +# for primas
deleted secret

2022-07-02 12:40 UTC, mable-pmyip commented
@tardigrade425 Hi William, I just fixed the issues you mentioned, can you pls review again. Thanks.

2022-07-02 14:46 UTC, mable-pmyip commented on deployment.yaml
> +  DATABASE_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbkBjbHVzdGVyMC5vcG1uZS5tb25nb2RiLm5ldC9hLWNvbW9zdXM/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
Passing the encoded database_url here in the secret def file.

2022-07-03 05:50 UTC, tardigrade425 commented on CI-CD/Jenkinsfile.Mable
> +		  steps {
缩进，对齐

2022-07-03 05:50 UTC, tardigrade425 commented on CI-CD/Jenkinsfile.Mable
> +		  steps {
下同

2022-07-03 05:50 UTC, tardigrade425 commented on Dockerfile.Mable
> +ENV PORT 3100
这里的环境变量和deployment中的有什么关系？

2022-07-04 12:08 UTC, mable-pmyip commented on Dockerfile.Mable
> +ENV PORT 3100
Not quite sure, I am just using the DATABASE_URL at the moment (in deployment.yaml file)
but may be required when using terraform to deploy. 
@AlexXin14 Can you please confirm that?

2022-07-04 13:05 UTC, NorrisWu0 commented
Nope. That error means either db is not connected, or your db schema has not been updated. Try running `db push` before building the backend code.

2022-07-05 03:05 UTC, mable-pmyip commented
> Nope. That error means either db is not connected, or your db schema has not been updated. Try running `yarn prisma db push` before building the backend code.
Thanks, will have a try tonight

2022-07-05 10:37 UTC, mable-pmyip commented
> Nope. That error means either db is not connected, or your db schema has not been updated. Try running `yarn prisma db push` before building the backend code.

The  `yarn prisma db push` doesn't work for me, but it's working fine when I created a new  account. 
Seems like because the old account doesn't have the createdAt field as I created it a few weeks ago. Anyway, it's all working now. Thanks! 
![image](https://user-images.githubusercontent.com/94888732/177309697-69b5f202-6417-47ef-98aa-db842deff399.png)

2022-07-08 02:18 UTC, tardigrade425 requested changes

2022-07-08 02:18 UTC, tardigrade425 commented on CI-CD/Jenkinsfile.Mable
> +        registryCredential = 'ecr:us-east-1:awscreds'
对齐

2022-07-08 02:18 UTC, tardigrade425 commented on CI-CD/Jenkinsfile.Mable
> +	    steps{
缩进

2022-07-08 02:18 UTC, tardigrade425 commented on CI-CD/Jenkinsfile.Mable
> +	    steps{
下面还有

2022-07-08 02:18 UTC, tardigrade425 commented on Dockerfile.Mable
> +ENV DATABASE_URL mongodb
k8s secrets中的变量，这里是否还有必要？

2022-07-08 02:18 UTC, tardigrade425 commented on CI-CD/Jenkinsfile.Mable
> +        nodejs 'node'
node版本号

2022-07-14 11:25 UTC, closed without merging