[AC-102: Feature] Replacing sendEmail with sls function
A-Comosus/comosus-server pull request #23
Opened 2022-07-11 07:53 UTC by miaozhaod

### Provide description as to what you have done in this pr.
To replace the `sendEmail` with the lambda function, so maybe I shouldn't PR this until the lambda function is approved and deployed, but just pushed for now
 
### Provide screenshots or videos that the function is working.
<img width="1087" alt="Screen Shot 2022-07-11 at 3 42 52 pm" src="https://user-images.githubusercontent.com/89491470/178213972-899cab1c-a15b-4b9e-81ff-b0905463449e.png">
<img width="977" alt="Screen Shot 2022-07-11 at 3 43 10 pm" src="https://user-images.githubusercontent.com/89491470/178214015-e05d158a-e736-4a14-b922-c65fa833387c.png">

### Provide screenshots of no warning, error in console.
as above

### Developer Checklist

#### That the feature you have worked on has its...
- [x] relevant information updated in `README.MD`
~~- [ ] swagger doc created/updated so that other developers can read the related documentation.~~
- [x] logging included/updated so that we can debug errors when the app is live in the UAT environment.
~~- [ ] unit tests created/updated so that we can integrate this new release and sleep without worries at night/day.~~

#### When you finished, you will want to make sure you have...
- [x] No merge conflict with `develop` branch.
- [x] Check PR title is correct, (i.e `[AC-xx: Feature] Create pull request template`).
- [x] Check your app will run without crashes.
- [x] Check if there's hard coded values.
- [x] No `//eslint-disable-next-line no-unused-vars`, unless otherwise specified.
- [x] No unnecessary spaces between lines of code.
- [x] Check you are using `camelCase && PascalCase` correctly.
- [x] Check you named your code properly.
- [x] Remove unused comments.

2022-07-14 11:52 UTC, NorrisWu0 requested changes

2022-07-14 11:52 UTC, NorrisWu0 commented on src/resource/auth/auth.service.ts
> +      await axios.post(this.configService.get(EnvVar.LambdaSendEmailEndpoint), {
We have a common module to handle all our outgoing HTTP requests, it's best if we have a separate function in `axios.service.ts` to handle post request of this lambda function as well,

2022-07-17 05:09 UTC, miaozhaod commented on src/resource/auth/auth.service.ts
> +      await axios.post(this.configService.get(EnvVar.LambdaSendEmailEndpoint), {
updated this one

2022-07-17 06:17 UTC, NorrisWu0 approved these changes

2022-07-17 06:17 UTC, merged