[AC-xx: CI-CD] Create jenkinsfile to deploy to tf cluster
A-Comosus/comosus-server pull request #29
Opened 2022-07-23 10:04 UTC by mable-pmyip

### Provide description as to what you have done in this pr.
### Provide screenshots or videos that the function is working.
![image](https://user-images.githubusercontent.com/94888732/180600492-b3159410-3f02-43c7-95ac-2009b58db8b0.png)

2022-07-23 10:57 UTC, tardigrade425 requested changes

2022-07-23 10:57 UTC, tardigrade425 commented on CI-CD/Jenkinsfile.Mable
> +                git branch: 'ci-cd/jenkins-tf-Mable ', url: 'https://github.com/A-Comosus/comosus-server.git'
fetch这个branch是做什么的？

2022-07-23 10:57 UTC, tardigrade425 commented on Dockerfile.Mable
> +FROM node:alpine AS deps
这个版本是干什么？

2022-07-23 10:57 UTC, tardigrade425 commented on Dockerfile.Mable
> +FROM node:alpine AS deps
固定与其他版本一致

2022-07-23 10:57 UTC, tardigrade425 commented on Dockerfile.Mable
> +FROM node:alpine AS runner
与前端node版本一致

2022-07-23 10:57 UTC, tardigrade425 commented on CI-CD/Jenkinsfile.Mable
> +        nodejs 'node18.4.0'
确认一下版本

2022-07-24 01:56 UTC, mable-pmyip commented on Dockerfile.Mable
> +FROM node:alpine AS deps
I think the other dockerfile user this image ``node:alpine`` as well 
https://github.com/A-Comosus/comosus-server/blob/develop/Dockerfile.Alex#L2
https://github.com/A-Comosus/comosus-client/blob/develop/Dockerfile.Alex#L2

2022-07-24 01:56 UTC, mable-pmyip commented on Dockerfile.Mable
> +FROM node:alpine AS runner
same as this one https://github.com/A-Comosus/comosus-server/blob/develop/Dockerfile.Alex#L18

2022-07-24 01:56 UTC, mable-pmyip commented on CI-CD/Jenkinsfile.Mable
> +                git branch: 'ci-cd/jenkins-tf-Mable ', url: 'https://github.com/A-Comosus/comosus-server.git'
for testing only, updated to "develop" branch now

2022-07-24 01:57 UTC, mable-pmyip commented on CI-CD/Jenkinsfile.Mable
> +        nodejs 'node18.4.0'
turns out this tool isn't needed, I removed it

2022-07-25 07:46 UTC, tardigrade425 submitted a review, later dismissed

2022-07-25 07:46 UTC, tardigrade425 commented on Dockerfile.Mable
> +FROM node:alpine AS runner
alphine是个简化的版本，要和developer使用的版本保持一致

2022-07-25 11:22 UTC, AlexXin14 approved these changes

2022-07-25 11:23 UTC, merged